Mp update getting started
datacoves/docs pull request #21
Opened 2024-04-12 00:13 UTC by mayrapena1324

2024-05-01 23:34 UTC, noel requested changes

2024-05-01 23:36 UTC, mayrapena1324 commented on docs/_sidebar.md
> +    - [Update Repository](getting-started/Admin/configure-repository.md)
Well they are updating their repository to include files that it didnt before. I figured it could be its own thing. This wont be too much of an issue once we introduce those new CLI tools in the next sprint.

2024-05-01 23:43 UTC, mayrapena1324 commented on docs/getting-started/Admin/configure-repository.md
> +      threads: [1 or more]  # Optional, default 1
Ill set it to 4

2024-05-01 23:46 UTC, mayrapena1324 commented on docs/how-tos/airflow/initial-setup.md
> +### Logs Configuration - Private Deployment ONLY
Thats what this says no?

2024-05-02 23:00 UTC, mayrapena1324 commented on docs/how-tos/airflow/initial-setup.md
> +Once configured, you will need to configure your CICD process to clone your project into the S3 bucket.
That can be a new branch :)

2024-05-02 23:01 UTC, mayrapena1324 commented on docs/how-tos/airflow/send-emails.md
> +- **Port:** TLS encryption on port 587. If you’d like to implement SSL encryption, use port 465.
Ill leave it for now and update once the feature is released

2024-05-04 14:39 UTC, noel approved these changes

2024-05-04 14:39 UTC, merged