Create databricks doc page
datacoves/docs pull request #35
Opened 2024-07-03 15:13 UTC by mayrapena1324

2024-07-03 18:03 UTC, noel commented on docs/how-tos/airflow/run-databricks-notebook.md
> +**Step 3:** Look at the URL bar and copy the value after `/clusters/` and before the `?` character. It will look something like this: `0123-5678910-abcdefghijk`.
this might be in the cluster config as well

2024-07-03 18:04 UTC, noel commented on docs/how-tos/airflow/run-databricks-notebook.md
> +        "run_name": "your-run-name",  # Update with a unique name
what is this used for?

2024-07-03 20:24 UTC, mayrapena1324 commented on docs/how-tos/airflow/run-databricks-notebook.md
> +Sign into your Databricks account and look at the URL. The host value is the bit after `https://` up until `.com` and it will look something like this: `abc-123-defghi-45jk.cloud.databricks.com`
Fixed

2024-07-03 20:24 UTC, mayrapena1324 commented on docs/how-tos/airflow/run-databricks-notebook.md
> +- **API Token:** If you do not have admin privileges, work with an admin to get the token. Follow the [Databricks documentation here](https://docs.databricks.com/en/dev-tools/auth/pat.html).
Fixed

2024-07-03 20:24 UTC, mayrapena1324 commented on docs/how-tos/airflow/run-databricks-notebook.md
> +**Step 3:** Look at the URL bar and copy the value after `/clusters/` and before the `?` character. It will look something like this: `0123-5678910-abcdefghijk`.
Fixed

2024-07-03 20:25 UTC, mayrapena1324 commented on docs/how-tos/airflow/run-databricks-notebook.md
> +        "run_name": "your-run-name",  # Update with a unique name
That is described in the Understanding the DAG section

2024-07-05 21:22 UTC, sconley-datacoves commented
@noel Just a ping to put this back on your radar in case it has fallen off :)

2024-08-15 16:12 UTC, noel requested changes

2024-08-15 16:12 UTC, noel commented on docs/how-tos/airflow/customize-worker-environment.md
> +        "schedule": "0 0 1 */12 *",
check which is the right one

2024-08-15 16:12 UTC, noel commented on docs/how-tos/airflow/request-resources-on-workers.md
> +        "schedule": "0 0 1 */12 *",
check this too

2024-08-15 16:12 UTC, noel commented on docs/how-tos/airflow/run-adf-pipeline.md
> +
remove extra lines

2024-08-15 16:12 UTC, noel commented on docs/how-tos/airflow/run-databricks-notebook.md
> +- **DATABRICKS_NOTEBOOK_PATH**
consider not being a variable

2024-08-15 16:12 UTC, noel commented on docs/how-tos/airflow/run-databricks-notebook.md
> +DATABRICKS_NOTEBOOK_PATH = "/Workspace/Repos/mayra@datacoves.com/databricks_notebooks/insert_into_raw"
DATABRICKS_REPO_NOTEBOOK_PATH

2024-08-15 16:12 UTC, noel commented on docs/how-tos/airflow/send-slack-notifications.md
> -from kubernetes.client import models as k8s
Check Teams version and do the same

2024-08-15 16:12 UTC, noel commented on docs/how-tos/datahub/how_to_datahub_cli.md
> +1. Open a terminal in VSCode and run the following command:
VSCode vs VS Code

2024-08-15 22:02 UTC, mayrapena1324 commented on docs/how-tos/airflow/customize-worker-environment.md
> +        "schedule": "0 0 1 */12 *",
Fixed

2024-08-15 22:08 UTC, mayrapena1324 commented on docs/how-tos/airflow/request-resources-on-workers.md
> +        "schedule": "0 0 1 */12 *",
Fixed

2024-08-15 22:08 UTC, mayrapena1324 commented on docs/how-tos/airflow/run-adf-pipeline.md
> +
Fixed

2024-08-15 22:14 UTC, mayrapena1324 commented on docs/how-tos/datahub/how_to_datahub_cli.md
> +1. Open a terminal in VSCode and run the following command:
Fixed

2024-08-15 22:15 UTC, mayrapena1324 commented on docs/how-tos/airflow/send-slack-notifications.md
> -from kubernetes.client import models as k8s
This one was already simplified

2024-08-15 22:55 UTC, mayrapena1324 commented on docs/how-tos/airflow/run-databricks-notebook.md
> +DATABRICKS_NOTEBOOK_PATH = "/Workspace/Repos/mayra@datacoves.com/databricks_notebooks/insert_into_raw"
Fixed

2024-09-05 21:25 UTC, noel requested changes

2024-09-05 21:25 UTC, noel commented on docs/_sidebar.md
> +    - [Notifications - Send Slack notifications](/how-tos/airflow/send-slack-notifications.md)
@mayrapena1324 shouldnt this be higher.....

2024-09-05 21:25 UTC, noel commented on docs/_sidebar.md
> +    - [Add a Data Set](/how-tos/superset/how_to_data_set.md)
do they call is Dataset or Data Set?

2024-09-05 21:25 UTC, noel commented on docs/how-tos/airflow/customize-worker-environment.md
> +        executor_config=TRANSFORM_CONFIG,
I wonder if we should call this WORKER_CONFIG (update above as well)

2024-09-05 21:25 UTC, noel commented on docs/how-tos/airflow/customize-worker-environment.md
>        image: <IMAGE REPO>:<IMAGE TAG>
are we overriding images or worker configs?

2024-09-05 21:25 UTC, noel commented on docs/how-tos/airflow/request-resources-on-workers.md
> +        executor_config=TRANSFORM_CONFIG
same as the other, WORKER_CONFIG?

2024-09-05 21:25 UTC, noel commented on docs/how-tos/airflow/request-resources-on-workers.md
> +        executor_config=TRANSFORM_CONFIG
check, maybe we cant do this bec when it is generated from yml it will get the name automatically.

2024-09-06 22:04 UTC, mayrapena1324 commented on docs/_sidebar.md
> +    - [Notifications - Send Slack notifications](/how-tos/airflow/send-slack-notifications.md)
Fixed

2024-09-06 22:15 UTC, mayrapena1324 commented on docs/_sidebar.md
> +    - [Add a Data Set](/how-tos/superset/how_to_data_set.md)
Dataset. Changed it.

2024-09-06 22:22 UTC, mayrapena1324 commented on docs/how-tos/airflow/customize-worker-environment.md
> +        executor_config=TRANSFORM_CONFIG,
We call it TRANSFORM_CONFIG because that is what is generated when using dbt-coves

2024-09-06 22:24 UTC, mayrapena1324 commented on docs/how-tos/airflow/customize-worker-environment.md
> +        executor_config=TRANSFORM_CONFIG,
So if I change it to load it will be rendered as LOAD_CONFIG.

2024-09-06 22:25 UTC, mayrapena1324 commented on docs/how-tos/airflow/request-resources-on-workers.md
> +        executor_config=TRANSFORM_CONFIG
It is being generated

2024-09-06 22:27 UTC, mayrapena1324 commented on docs/how-tos/airflow/customize-worker-environment.md
>        image: <IMAGE REPO>:<IMAGE TAG>
In this one we are showing them how to use a custom image and in docs/how-tos/airflow/request-resources-on-workers.md we show them how to edit the resource configs

2024-09-11 22:47 UTC, noel approved these changes

2024-09-11 22:49 UTC, merged